### ISSUE TITLE
Pixel Aspect Ratio (not spam!)

### ISSUE THREAD

**Issue by gasparschott** [ImageProcessing-ElectronicPublications/scantailor-experimental#28]
This was not a spam message. I guess I should explain in detail what's going on. 

When I process an ordinary jpg through scantailor-experimental and open the resulting output tiff in Photoshop, the image appears squashed horizontally about 50% and Photoshop displays a message about the Pixel Aspect Ratio being set. I have to change this by going in Photoshop to View > Pixel Aspect Ratio > Square. Then the image displays correctly. 

I have used other versions of Scantailor and have not had this problem. I'm running Scantailor-experimental on an M1 MacBookPro.

**Comment by plzombie** [comment]
@gasparschott Can you try latest commit?

If not works, can you get the result of ```tiffinfo your_image.tif```?

**Comment by gasparschott** [comment]
Will do, when I get the chance. Thanks.

**Comment by gasparschott** [comment]
Yes, that seems to have fixed the problem. Thanks!

**Comment by noobie-iv** [comment]
The pixel aspect ratio was removed by the author of the experimental branch of the program at the very beginning of its creation. Therefore, you need to correct the aspect ratio in advance in some other program before processing in STEX, and assign the correct value after. By the way, STA also does not handle rectangular pixels correctly if the image is rotated - it doubles squareness instead of straightening.

Also, the dewarping mode gives a result with not quite square pixels, here we really need to add aspect ratio settings at the dewarping stage or immediately after it. And we need guides - to adjust pixel sizes until the overall page sizes match other pages.
